# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Github Actions dependabot checks
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/setup-environment"
    schedule:
      interval: "monthly"
    assignees:
      - "jordanshatford"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "jordanshatford"

  # API dependabot checks
  - package-ecosystem: "docker"
    directory: "/apps/api"
    schedule:
      interval: "monthly"
    assignees:
      - "jordanshatford"
  - package-ecosystem: "pip"
    directory: "/apps/api"
    schedule:
      interval: "monthly"
    assignees:
      - "jordanshatford"

  # TypeScript packages dependabot checks
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "jordanshatford"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "jordanshatford"
