version: '3'

services:
  api:
    build:
      context: ./apps/api
      target: production
    image: youtubeaudiodownloader-api:latest
    restart: always
    environment:
      ALLOWED_ORIGIN: http://localhost:5173
    ports:
      - 8080:8080
  web:
    build:
      context: ./apps/web
      target: production
    image: youtubeaudiodownloader-web:latest
    restart: always
    environment:
      VITE_SERVER_ADDR: http://localhost:8080
    ports:
      - 5173:5173
    depends_on:
      - api
