version: '3'

services:
  server:
    build: ./server
    restart: always
    ports:
      - '${SERVER_PORT}:8080'
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - SERVER_ADDR=${SERVER_HOST}:${SERVER_PORT}
    restart: always
    ports:
      - '${CLIENT_PORT}:5000'
    depends_on:
      - server