version: '3'

services:
  api:
    extends:
      file: docker-compose.yml
      service: api
    build:
      target: api-development
    volumes:
      - ./apps/api:/workspace/api
  web:
    extends:
      file: docker-compose.yml
      service: web
    build:
      target: web-development
    ports:
      - 5173:5173
      - 24678:24678
    volumes:
      - .:/workspace
      - /workspace/node_modules
      - /workspace/apps/web/node_modules
      - /workspace/packages/client/node_modules
      - /workspace/packages/config/node_modules
      - /workspace/packages/ui/node_modules

