version: '3'

services:
  api:
    extends:
      file: docker-compose.yml
      service: api
    build:
      target: development
    volumes:
      - ./apps/api:/api
  web:
    extends:
      file: docker-compose.yml
      service: web
    build:
      target: development
    ports:
      - 5173:5173
      - 24678:24678
    volumes:
      - ./apps/web:/web
      - /web/node_modules
