version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - 8000:8080
    environment:
      - ALLOWED_ORIGIN=http://localhost:3000
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 3000:3000
    environment:
      - VITE_SERVER_ADDR=http://localhost:8000
    depends_on:
      - backend
