version: '3'

services:
  backend:
    build:
      context: ./backend
      target: production
    image: youtubeaudiodownloader-backend:latest
    restart: always
    environment:
      ALLOWED_ORIGIN: http://localhost:5173
    ports:
      - 8080:8080
  frontend:
    build:
      context: ./frontend
      target: production
    image: youtubeaudiodownloader-frontend:latest
    restart: always
    environment:
      VITE_SERVER_ADDR: http://localhost:8080
    ports:
      - 5173:5173
    depends_on:
      - backend
