version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - 8000:8080
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 80:5000
    environment:
      - VITE_SERVER_ADDR=http://0.0.0.0:8000
    depends_on:
      - backend
