version: '3'

services:
  api:
    build:
      context: .
      target: api-production
    image: yd/api:latest
    restart: always
    environment:
      ALLOWED_ORIGIN: http://localhost:5173
    ports:
      - 8080:8080
  cli:
    build:
      context: .
      target: cli
    image: yd/cli:latest
  web:
    build:
      context: .
      target: web-production
    image: yd/web:latest
    restart: always
    environment:
      VITE_SERVER_ADDR: http://localhost:8080
    ports:
      - 5173:5173
    depends_on:
      - api
