version: '3.3'

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - 8000:8080
    environment:
      - ALLOWED_ORIGIN=http://localhost:3000
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_SERVER_ADDR=http://localhost:8000
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
