version: '3.3'

services:
  backend:
    build:
      context: ./backend
    image: youtube-to-mp3-backend:latest
    restart: always
    environment:
      DEBUG: 1
      HOST: 0.0.0.0
      PORT: 8080
      ALLOWED_ORIGIN: http://localhost:5173
    ports:
      - 8000:8080
    volumes:
      - ./backend:/backend
  frontend:
    build:
      context: ./frontend
    image: youtube-to-mp3-frontend:latest
    restart: always
    environment:
      VITE_SERVER_ADDR: http://localhost:8000
    ports:
      - 5173:5173
      - 24678:24678
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
