name: Setup environment
description: Setup CI environment for running YouTube Audio Downloader
inputs:
  node-version:
    description: Node version to use
    required: false
    default: '18.x'
  pnpm-version:
    description: PNPM version to use
    required: false
    default: 8
  python-version:
    description: Python version to use
    required: false
    default: '3.11'

runs:
  using: 'composite'
  steps:
    - name: Setup PNPM
      uses: pnpm/actions-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
