[project]
name = "youtube-downloader-api"
version = "1.0.0"
description = "API to search and download YouTube videos in various formats."
requires-python = ">=3.11"
license = {text = "MIT License"}
authors = [
    {name = "Jordan Shatford", email = "jordanshatford@live.com"},
]

[project.urls]
Repository = "https://github.com/jordanshatford/youtube-downloader"
