[tool.poetry]
package-mode = false
name = "@yd/api"
version = "1.0.0"
description = "API to search and download YouTube videos in various formats."
authors = []
license = "MIT"


[tool.poetry.dependencies]
python = "^3.11"
fastapi = "0.111.0"
mutagen = "1.47.0"
pydantic = ">=2.1.1,<3.0.0"
sse-starlette = "2.1.0"
uvicorn = "0.29.0"
yt-dlp = "2024.5.26"

[tool.poetry.group.dev.dependencies]
pre-commit = "3.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
