name: Build, Lint, and Check Frontend

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        node-version: [14.x, 16.x, 17.x]
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Setup node version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run diagnostics check
        run: npm run check -- --output machine
      - name: Run linting check
        run: npm run lint
      - name: Run build
        run: npm run build
