name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  pull_request:
  workflow_dispatch:

jobs:
  frontend:
    name: Frontend (Build, Lint, Check)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        node-version: [16.x, 18.x]
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run linting check
        run: npm run lint
      - name: Run diagnostics check
        run: npm run check -- --output machine
      - name: Run build
        run: npm run build
