name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  frontend:
    name: Frontend (Build, Lint, Check)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        node-version: [18.x, 20.x]
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run linting check
        run: npm run lint
      - name: Run diagnostics check
        run: npm run check -- --output machine
      - name: Run build
        run: npm run build

  backend:
    name: Backend (Pre-commit)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.x]
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --config ./backend/.pre-commit-config.yaml --all-files
      - uses: pre-commit-ci/lite-action@v1.0.1
        if: always()