name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  pull_request:
    types: [opened, synchronize]
    paths: 'frontend/**'

jobs:
  frontend:
    name: Frontend
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        node-version: [16.x, 17.x, 18.x]
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Setup node version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run linting check
        run: npm run lint
      - name: Run build
        run: npm run build
      - name: Run diagnostics check
        run: npm run check -- --output machine
